# Generated by Django 6.0.6 on 2026-07-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='clinic_or_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
