# Generated by Django 6.0.6 on 2026-07-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_doctorvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Raw PDF or image file', upload_to='lab_reports/%Y/%m/%d/')),
                ('test_type', models.CharField(choices=[('Blood Test', 'Blood Test'), ('USG', 'USG'), ('X-Ray', 'X-Ray'), ('ECG', 'ECG'), ('MRI', 'MRI'), ('Other', 'Other')], max_length=50)),
                ('report_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Flat key-value schema extracted by Gemini')),
                ('summary', models.TextField(blank=True, help_text='AI plain-English breakdown summary', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PARSED', 'Successfully Parsed'), ('FAILED', 'Extraction Failed')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_reports', to='users.doctorvisit')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
