# Generated by Django 6.0.6 on 2026-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Flat key-value schema extracted by Gemini', null=True),
        ),
    ]
