# Generated by Django 6.0.6 on 2026-07-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('labreports', '0003_alter_labreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_reports', to='clinical.doctorvisit'),
        ),
    ]
