# Generated by Django 6.0.6 on 2026-07-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0004_alter_labreport_visit'),
        ('users', '0002_doctorvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorVisit',
        ),
    ]
